"""Acceptance tests: the finished program must pass all of these. Do not edit this file.
They only use the command line (tasktracker.cli.main), so you are free to design the inside."""

import json

import pytest
from tasktracker.cli import main

TODAY = "2026-10-10"


@pytest.fixture
def run(tmp_path, capsys):
    """run("add", "Buy milk") -> (exit_code, stdout, stderr), using a temporary tasks file."""
    file = tmp_path / "tasks.json"

    def _run(*args: str, today: str = TODAY):
        argv = ["--file", str(file), "--today", today, *args]
        try:
            code = main(argv)
        except SystemExit as e:  # argparse exits for bad options
            code = e.code
        captured = capsys.readouterr()
        return (code or 0), captured.out, captured.err

    _run.file = file  # type: ignore[attr-defined]
    return _run


def test_add_prints_confirmation_and_creates_the_file(run):
    code, out, _ = run("add", "Buy milk")
    assert code == 0
    assert out.strip() == "Added #1: Buy milk"
    assert run.file.exists()


def test_ids_increase_and_are_never_reused(run):
    run("add", "One")
    run("add", "Two")
    run("remove", "2")
    _, out, _ = run("add", "Three")
    assert out.strip() == "Added #3: Three"


def test_list_format_and_empty_message(run):
    code, out, _ = run("list")
    assert code == 0 and out.strip() == "No tasks."
    run("add", "Buy milk", "--priority", "high", "--due", "2026-10-20")
    run("add", "Call Sara")
    _, out, _ = run("list")
    assert out.splitlines() == [
        "#1 [ ] (high) Buy milk  due 2026-10-20",
        "#2 [ ] (normal) Call Sara",
    ]


def test_list_orders_by_priority_then_due_date_then_id(run):
    run("add", "normal, no date")  # 1
    run("add", "low, early", "--priority", "low", "--due", "2026-10-11")  # 2
    run("add", "high, late", "--priority", "high", "--due", "2026-12-01")  # 3
    run("add", "high, early", "--priority", "high", "--due", "2026-10-15")  # 4
    run("add", "normal, dated", "--due", "2026-10-12")  # 5
    _, out, _ = run("list")
    ids = [line.split()[0] for line in out.splitlines()]
    assert ids == ["#4", "#3", "#5", "#1", "#2"]


def test_done_hides_the_task_until_all_is_used(run):
    run("add", "Buy milk")
    run("add", "Call Sara")
    code, out, _ = run("done", "1")
    assert code == 0 and out.strip() == "Completed #1"
    _, out, _ = run("list")
    assert out.splitlines() == ["#2 [ ] (normal) Call Sara"]
    _, out, _ = run("list", "--all")
    assert out.splitlines() == ["#1 [x] (normal) Buy milk", "#2 [ ] (normal) Call Sara"]


def test_remove_deletes_the_task(run):
    run("add", "Buy milk")
    code, out, _ = run("remove", "1")
    assert code == 0 and out.strip() == "Removed #1"
    _, out, _ = run("list", "--all")
    assert out.strip() == "No tasks."


@pytest.mark.parametrize("command", ["done", "remove"])
def test_unknown_id_is_an_error_with_exit_code_1(run, command):
    run("add", "Buy milk")
    code, out, err = run(command, "9")
    assert code == 1 and out == ""
    assert "No task #9" in err


@pytest.mark.parametrize("title", ["", "   ", "x" * 81])
def test_invalid_title_exits_with_2(run, title):
    code, out, err = run("add", title)
    assert code == 2 and out == ""
    assert "title" in err.lower()
    assert not run.file.exists() or json.loads(run.file.read_text(encoding="utf-8"))["tasks"] == []


def test_title_is_trimmed_and_80_characters_is_allowed(run):
    _, out, _ = run("add", "  padded  ")
    assert out.strip() == "Added #1: padded"
    code, _, _ = run("add", "y" * 80)
    assert code == 0


def test_invalid_priority_exits_with_2(run):
    code, _, err = run("add", "Buy milk", "--priority", "urgent")
    assert code == 2 and err


@pytest.mark.parametrize("due", ["tomorrow", "2026-13-01", "10/10/2026", "2026-02-30"])
def test_invalid_due_date_exits_with_2(run, due):
    code, out, err = run("add", "Buy milk", "--due", due)
    assert code == 2 and out == ""
    assert "due" in err.lower()


def test_stats_counts_open_done_and_overdue(run):
    run("add", "late", "--due", "2026-10-01")  # overdue
    run("add", "today", "--due", TODAY)  # due today is not overdue
    run("add", "future", "--due", "2026-11-01")
    run("add", "finished late", "--due", "2026-09-01")
    run("done", "4")  # done tasks are never overdue
    _, out, _ = run("stats")
    assert out.strip() == "open: 3, done: 1, overdue: 1"


def test_data_is_stored_as_json_and_survives_between_runs(run):
    run("add", "Buy milk", "--priority", "low", "--due", "2026-10-20")
    data = json.loads(run.file.read_text(encoding="utf-8"))
    assert data["next_id"] == 2
    assert len(data["tasks"]) == 1
    task = data["tasks"][0]
    assert task["id"] == 1 and task["title"] == "Buy milk"
    assert task["priority"] == "low" and task["due"] == "2026-10-20" and task["done"] is False
    assert task["created"] == TODAY


def test_non_ascii_titles_round_trip(run):
    run("add", "اشتري الخبز")
    _, out, _ = run("list")
    assert "اشتري الخبز" in out


def test_corrupt_file_is_reported_not_crashed(run):
    run.file.write_text("{not json", encoding="utf-8")
    code, out, err = run("list")
    assert code == 1 and out == ""
    assert "error" in err.lower()


def test_wrong_shape_is_reported_too(run):
    run.file.write_text('{"tasks": "oops"}', encoding="utf-8")
    code, _, err = run("list")
    assert code == 1 and "error" in err.lower()
