"""Module 01 acceptance tests: URLs, views and templates. Do not edit this file.

Run:  python manage.py test circles.tests.test_architecture
"""

from django.apps import apps
from django.conf import settings
from django.test import SimpleTestCase, TestCase
from django.urls import reverse


class WiringTests(SimpleTestCase):
    """These pass from the start: they check the project is wired the way the lesson explains."""

    def test_the_circles_app_is_installed(self):
        assert apps.is_installed("circles")

    def test_settings_use_cairo_time(self):
        assert settings.TIME_ZONE == "Africa/Cairo" and settings.USE_TZ is True

    def test_admin_is_mounted(self):
        response = self.client.get("/admin/login/")
        assert response.status_code == 200


class HealthTests(SimpleTestCase):
    def test_returns_json_ok(self):
        response = self.client.get("/health/")
        assert response.status_code == 200
        assert response.json() == {"status": "ok"}
        assert response["Content-Type"] == "application/json"

    def test_only_get_is_allowed(self):
        for method in ("post", "put", "delete"):
            response = getattr(self.client, method)("/health/")
            assert response.status_code == 405, method


class PathParameterTests(SimpleTestCase):
    def test_hello_uses_the_name_from_the_url(self):
        response = self.client.get("/hello/Sara/")
        assert response.status_code == 200
        assert response.content.decode() == "Hello, Sara!"

    def test_hello_supports_arabic_names(self):
        response = self.client.get("/hello/سارة/")
        assert response.content.decode() == "Hello, سارة!"

    def test_a_name_cannot_contain_a_slash(self):
        assert self.client.get("/hello/a/b/").status_code == 404

    def test_add_converts_the_parts_to_integers(self):
        response = self.client.get("/add/2/40/")
        assert response.json() == {"sum": 42}

    def test_add_rejects_non_integers_with_404(self):
        assert self.client.get("/add/x/2/").status_code == 404
        assert self.client.get("/add/1.5/2/").status_code == 404


class TemplateTests(TestCase):
    def test_about_renders_its_template_with_context(self):
        response = self.client.get("/about/")
        assert response.status_code == 200
        self.assertTemplateUsed(response, "circles/about.html")
        assert response.context["title"] == "About Gameya"
        self.assertContains(response, "About Gameya")

    def test_about_template_escapes_html_in_the_title(self):
        # Templates escape variables automatically; this checks you used {{ title }}, not |safe.
        response = self.client.get("/about/")
        self.assertNotContains(response, "<script>")


class RoutingTests(SimpleTestCase):
    def test_every_route_has_a_name(self):
        assert reverse("health") == "/health/"
        assert reverse("hello", args=["Sara"]) == "/hello/Sara/"
        assert reverse("add", args=[1, 2]) == "/add/1/2/"
        assert reverse("about") == "/about/"

    def test_unknown_urls_are_404(self):
        assert self.client.get("/nope/").status_code == 404
