"""Module 03 acceptance tests: the admin and the forms. Do not edit this file.

Run:  python manage.py test circles.tests.test_admin_forms

These tests use the Module 02 models. Finish those first.
"""

from datetime import date

from django.contrib import admin
from django.contrib.auth import get_user_model
from django.test import SimpleTestCase, TestCase
from django.urls import reverse

# Import the module, not the names: a missing form then fails only its own tests.
from circles import forms as circle_forms
from circles.models import Gameya, Member, Payment, PayoutSlot


def model_admin(model):
    """The ModelAdmin object registered for a model."""
    return admin.site.get_model_admin(model)


class AdminRegistrationTests(SimpleTestCase):
    def test_all_four_models_are_registered(self):
        for model in (Gameya, Member, Payment, PayoutSlot):
            with self.subTest(model=model.__name__):
                self.assertTrue(admin.site.is_registered(model))

    def test_gameya_page_edits_its_members_inline(self):
        inlines = model_admin(Gameya).inlines
        members_inline = [inline for inline in inlines if inline.model is Member]
        self.assertEqual(len(members_inline), 1)
        self.assertTrue(issubclass(members_inline[0], admin.TabularInline))

    def test_member_admin_shows_name_gameya_and_shares(self):
        shown = model_admin(Member).list_display
        for field in ("name", "gameya", "shares"):
            with self.subTest(field=field):
                self.assertIn(field, shown)

    def test_member_admin_can_be_searched_by_name_and_filtered_by_gameya(self):
        admin_obj = model_admin(Member)
        self.assertIn("name", admin_obj.search_fields)
        self.assertIn("gameya", admin_obj.list_filter)

    def test_payment_admin_shows_member_week_paid_on_and_amount(self):
        shown = model_admin(Payment).list_display
        for field in ("member", "week", "paid_on", "amount"):
            with self.subTest(field=field):
                self.assertIn(field, shown)

    def test_payout_slot_admin_shows_the_turn_number(self):
        self.assertIn("turn_number", model_admin(PayoutSlot).list_display)


class AdminPagesTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.superuser = get_user_model().objects.create_superuser(
            "admin", "admin@example.com", "not-a-real-password"
        )
        cls.gameya = Gameya.objects.create(
            name="Alpha", start_date=date(2026, 10, 11), weeks=10, share_value=500
        )
        cls.ali = Member.objects.create(gameya=cls.gameya, name="Ali", shares=1)
        cls.sara = Member.objects.create(gameya=cls.gameya, name="Sara", shares=2)

    def setUp(self):
        self.client.force_login(self.superuser)

    def test_every_changelist_loads_for_a_superuser(self):
        for name in ("gameya", "member", "payment", "payoutslot"):
            with self.subTest(model=name):
                response = self.client.get(reverse(f"admin:circles_{name}_changelist"))
                self.assertEqual(response.status_code, 200)

    def test_search_finds_members_by_name(self):
        response = self.client.get(reverse("admin:circles_member_changelist"), {"q": "Sar"})
        names = [member.name for member in response.context["cl"].result_list]
        self.assertEqual(names, ["Sara"])

    def test_the_gameya_page_lists_its_members(self):
        response = self.client.get(reverse("admin:circles_gameya_change", args=[self.gameya.pk]))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Ali")
        self.assertContains(response, "Sara")

    def test_admin_can_add_a_member(self):
        response = self.client.post(
            reverse("admin:circles_member_add"),
            {"gameya": self.gameya.pk, "name": "Omar", "shares": 1},
        )
        self.assertEqual(response.status_code, 302)
        self.assertTrue(Member.objects.filter(gameya=self.gameya, name="Omar").exists())

    def test_admin_rejects_a_duplicate_member_name_in_one_gameya(self):
        response = self.client.post(
            reverse("admin:circles_member_add"),
            {"gameya": self.gameya.pk, "name": "Ali", "shares": 1},
        )
        self.assertEqual(response.status_code, 200)  # the form is shown again with errors
        self.assertEqual(Member.objects.filter(name="Ali").count(), 1)


class PaymentFormTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.gameya = Gameya.objects.create(
            name="Alpha", start_date=date(2026, 10, 11), weeks=10, share_value=500
        )
        # Ali has two shares, so a week costs him 2 * 500 = 1000.
        cls.ali = Member.objects.create(gameya=cls.gameya, name="Ali", shares=2)

    def data(self, **overrides):
        values = {"member": self.ali.pk, "week": 1, "paid_on": "2026-10-11", "amount": 1000}
        values.update(overrides)
        return values

    def test_the_form_has_exactly_the_four_payment_fields(self):
        self.assertEqual(
            set(circle_forms.PaymentForm().fields), {"member", "week", "paid_on", "amount"}
        )

    def test_a_payment_of_exactly_the_weekly_due_is_valid(self):
        form = circle_forms.PaymentForm(data=self.data())
        self.assertTrue(form.is_valid(), form.errors)

    def test_paying_more_than_the_due_is_valid(self):
        form = circle_forms.PaymentForm(data=self.data(amount=1500))
        self.assertTrue(form.is_valid(), form.errors)

    def test_paying_less_than_the_due_is_rejected_on_amount(self):
        form = circle_forms.PaymentForm(data=self.data(amount=999))
        self.assertFalse(form.is_valid())
        self.assertIn("amount", form.errors)

    def test_a_week_outside_the_gameya_is_rejected(self):
        form = circle_forms.PaymentForm(data=self.data(week=11))
        self.assertFalse(form.is_valid())

    def test_a_second_payment_for_the_same_week_is_rejected(self):
        Payment.objects.create(member=self.ali, week=1, paid_on=date(2026, 10, 11), amount=1000)
        form = circle_forms.PaymentForm(data=self.data())
        self.assertFalse(form.is_valid())
        self.assertTrue(form.non_field_errors())

    def test_a_missing_member_is_reported_and_does_not_crash(self):
        form = circle_forms.PaymentForm(data=self.data(member=""))
        self.assertFalse(form.is_valid())
        self.assertIn("member", form.errors)


class JoinFormTests(SimpleTestCase):
    def test_a_valid_join_is_accepted(self):
        form = circle_forms.JoinForm(data={"name": "Sara", "shares": 2})
        self.assertTrue(form.is_valid(), form.errors)

    def test_the_name_is_stripped_of_spaces(self):
        form = circle_forms.JoinForm(data={"name": "  Sara  ", "shares": 1})
        self.assertTrue(form.is_valid(), form.errors)
        self.assertEqual(form.cleaned_data["name"], "Sara")

    def test_a_blank_name_is_rejected(self):
        form = circle_forms.JoinForm(data={"name": "   ", "shares": 1})
        self.assertFalse(form.is_valid())
        self.assertIn("name", form.errors)

    def test_the_name_admin_is_reserved_in_any_letter_case(self):
        form = circle_forms.JoinForm(data={"name": "ADMIN", "shares": 1})
        self.assertFalse(form.is_valid())
        self.assertIn("name", form.errors)

    def test_a_name_over_80_characters_is_rejected(self):
        form = circle_forms.JoinForm(data={"name": "x" * 81, "shares": 1})
        self.assertFalse(form.is_valid())
        self.assertIn("name", form.errors)

    def test_shares_must_be_between_1_and_5(self):
        for shares in (0, 6):
            with self.subTest(shares=shares):
                form = circle_forms.JoinForm(data={"name": "Sara", "shares": shares})
                self.assertFalse(form.is_valid())
                self.assertIn("shares", form.errors)
        for shares in (1, 5):
            with self.subTest(shares=shares):
                form = circle_forms.JoinForm(data={"name": "Sara", "shares": shares})
                self.assertTrue(form.is_valid(), form.errors)
