"""Module 02 acceptance tests for queries.py. Do not edit this file.

Run:  python manage.py test circles.tests.test_queries
"""

from datetime import date

from django.db.models import QuerySet
from django.test import TestCase

from circles import queries
from circles.models import Gameya, Member, Payment, PayoutSlot


class QueryTestCase(TestCase):
    """A small, known world: week 1 pays on 2026-10-10, week 2 on 10-17, week 3 on 10-24."""

    @classmethod
    def setUpTestData(cls):
        cls.g = Gameya.objects.create(
            name="Alf", start_date=date(2026, 10, 10), weeks=4, per_week=2, share_value=100
        )
        cls.ali = Member.objects.create(gameya=cls.g, name="Ali", shares=2)
        cls.sara = Member.objects.create(gameya=cls.g, name="Sara", shares=1)
        cls.omar = Member.objects.create(gameya=cls.g, name="Omar", shares=1)

        Payment.objects.create(member=cls.ali, week=1, paid_on=date(2026, 10, 5), amount=200)
        Payment.objects.create(member=cls.ali, week=2, paid_on=date(2026, 10, 4), amount=200)
        Payment.objects.create(member=cls.sara, week=1, paid_on=date(2026, 10, 6), amount=100)

        PayoutSlot.objects.create(gameya=cls.g, turn_number=1, member=cls.ali)
        PayoutSlot.objects.create(gameya=cls.g, turn_number=2, member=cls.sara)
        PayoutSlot.objects.create(gameya=cls.g, turn_number=3, member=cls.ali)
        PayoutSlot.objects.create(gameya=cls.g, turn_number=4)

        cls.other = Gameya.objects.create(
            name="Other", start_date=date(2026, 10, 10), weeks=2, share_value=50
        )
        stranger = Member.objects.create(gameya=cls.other, name="Stranger")
        Payment.objects.create(member=stranger, week=1, paid_on=date(2026, 10, 5), amount=999)


class UnpaidMembersTests(QueryTestCase):
    def names(self, week, today):
        return [m.name for m in queries.unpaid_members(self.g, week, today)]

    def test_returns_a_lazy_queryset(self):
        assert isinstance(queries.unpaid_members(self.g, 1, date(2026, 10, 12)), QuerySet)

    def test_lists_members_with_no_payment_once_the_week_has_started(self):
        assert self.names(1, date(2026, 10, 12)) == ["Omar"]

    def test_nobody_is_unpaid_before_the_week_starts(self):
        assert self.names(2, date(2026, 10, 12)) == []

    def test_a_week_is_unpaid_from_its_payout_day(self):
        assert self.names(1, date(2026, 10, 10)) == ["Omar"]
        assert self.names(1, date(2026, 10, 9)) == []

    def test_later_week(self):
        assert self.names(2, date(2026, 10, 18)) == ["Sara", "Omar"]

    def test_only_this_gameya_is_considered(self):
        assert "Stranger" not in self.names(1, date(2026, 10, 12))


class TotalCollectedTests(QueryTestCase):
    def test_sums_only_this_gameya(self):
        assert queries.total_collected(self.g) == 500

    def test_zero_when_there_are_no_payments(self):
        empty = Gameya.objects.create(
            name="Empty", start_date=date(2026, 1, 3), weeks=2, share_value=1
        )
        assert queries.total_collected(empty) == 0

    def test_takes_one_query(self):
        with self.assertNumQueries(1):
            queries.total_collected(self.g)


class MemberTotalsTests(QueryTestCase):
    def test_annotates_and_orders(self):
        rows = [(m.name, m.paid_total, m.paid_weeks) for m in queries.member_totals(self.g)]
        assert rows == [("Ali", 400, 2), ("Sara", 100, 1), ("Omar", 0, 0)]

    def test_is_a_single_query(self):
        with self.assertNumQueries(1):
            list(queries.member_totals(self.g))

    def test_returns_member_instances(self):
        assert all(isinstance(m, Member) for m in queries.member_totals(self.g))


class WeeklySummaryTests(QueryTestCase):
    def test_groups_payments_by_week(self):
        assert queries.weekly_summary(self.g) == [
            {"week": 1, "count": 2, "amount": 300},
            {"week": 2, "count": 1, "amount": 200},
        ]

    def test_is_a_single_query(self):
        with self.assertNumQueries(1):
            queries.weekly_summary(self.g)


class MembersWithTurnsTests(QueryTestCase):
    def test_counts_turns_and_skips_members_without_any(self):
        rows = [(m.name, m.turn_count) for m in queries.members_with_turns(self.g)]
        assert rows == [("Ali", 2), ("Sara", 1)]

    def test_is_a_single_query(self):
        with self.assertNumQueries(1):
            list(queries.members_with_turns(self.g))


class WeeksOwedTests(QueryTestCase):
    def test_everything_started_and_unpaid(self):
        assert queries.weeks_owed(self.omar, date(2026, 10, 25)) == [1, 2, 3]

    def test_paid_weeks_are_not_owed(self):
        assert queries.weeks_owed(self.ali, date(2026, 10, 25)) == [3]
        assert queries.weeks_owed(self.sara, date(2026, 10, 25)) == [2, 3]

    def test_weeks_that_have_not_started_are_not_owed(self):
        assert queries.weeks_owed(self.omar, date(2026, 10, 9)) == []
        assert queries.weeks_owed(self.omar, date(2026, 10, 10)) == [1]

    def test_never_goes_beyond_the_last_week(self):
        assert queries.weeks_owed(self.omar, date(2030, 1, 1)) == [1, 2, 3, 4]


class AdvancePaymentsTests(QueryTestCase):
    def test_only_payments_made_before_the_window_opened(self):
        result = queries.advance_payments(self.g)
        assert [(p.member.name, p.week) for p in result] == [("Ali", 2)]

    def test_loads_members_with_the_payments_in_one_query(self):
        with self.assertNumQueries(1):
            result = queries.advance_payments(self.g)
            assert [p.member.name for p in result] == ["Ali"]
