"""Module 05 acceptance tests: templates, inheritance and static files. Do not edit this file.

Run:  python manage.py test circles.tests.test_templates

These tests use the Module 02 models. They render HTML, so they also need the Module 04 and
Module 05 views and URLs. Finish those first.
"""

from datetime import date

from django.test import TestCase
from django.urls import reverse

from circles.models import Gameya, Member


def make_gameya(**overrides):
    values = {
        "name": "Alpha",
        "start_date": date(2026, 10, 11),
        "weeks": 10,
        "per_week": 1,
        "share_value": 500,
    }
    values.update(overrides)
    return Gameya.objects.create(**values)


class HomePageTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.alpha = make_gameya(name="Alpha")
        cls.beta = make_gameya(name="Beta")

    def test_lists_the_gameyas_by_name(self):
        response = self.client.get(reverse("home"))
        self.assertEqual(response.status_code, 200)
        html = response.content.decode()
        self.assertLess(html.index("Alpha"), html.index("Beta"))

    def test_each_gameya_links_to_its_page(self):
        response = self.client.get(reverse("home"))
        self.assertContains(response, reverse("gameya_page", args=[self.alpha.pk]))
        self.assertContains(response, reverse("gameya_page", args=[self.beta.pk]))

    def test_the_home_page_extends_the_base_layout(self):
        response = self.client.get(reverse("home"))
        self.assertTemplateUsed(response, "circles/home.html")
        self.assertTemplateUsed(response, "circles/base.html")

    def test_says_so_when_there_are_no_gameyas(self):
        Gameya.objects.all().delete()
        response = self.client.get(reverse("home"))
        self.assertContains(response, "No gameyas yet.")


class GameyaPageTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        # 10 weeks at 500 a share: the payout is 500 * 10 = 5000, and with one payout a
        # week the weekly pot is also 5000.
        cls.gameya = make_gameya(name="Alpha", weeks=10, per_week=1, share_value=500)
        # Ali has two shares, so his weekly due is 1000. Sara has one, so hers is 500.
        Member.objects.create(gameya=cls.gameya, name="Ali", shares=2)
        Member.objects.create(gameya=cls.gameya, name="Sara", shares=1)

    def page(self, gameya=None):
        return self.client.get(reverse("gameya_page", args=[(gameya or self.gameya).pk]))

    def test_shows_the_gameya_and_its_figures(self):
        response = self.page()
        self.assertEqual(response.status_code, 200)
        self.assertTemplateUsed(response, "circles/gameya_detail.html")
        self.assertContains(response, "Alpha")
        self.assertContains(response, "5000")

    def test_lists_each_member_with_their_weekly_due(self):
        response = self.page()
        self.assertContains(response, "Ali")
        self.assertContains(response, "Sara")
        self.assertContains(response, "1000")
        self.assertContains(response, "500")

    def test_member_names_are_escaped(self):
        Member.objects.create(gameya=self.gameya, name="<script>alert(1)</script>", shares=1)
        response = self.page()
        self.assertNotContains(response, "<script>alert(1)</script>")
        self.assertContains(response, "&lt;script&gt;alert(1)&lt;/script&gt;")

    def test_the_stylesheet_is_loaded_with_the_static_tag(self):
        self.assertContains(self.page(), "/static/circles/site.css")

    def test_a_gameya_without_members_says_so(self):
        empty = make_gameya(name="Empty")
        self.assertContains(self.page(empty), "No members yet.")

    def test_the_page_extends_the_base_layout(self):
        self.assertTemplateUsed(self.page(), "circles/base.html")

    def test_an_unknown_gameya_is_404(self):
        response = self.client.get(reverse("gameya_page", args=[9999]))
        self.assertEqual(response.status_code, 404)


class BaseLayoutTests(TestCase):
    def test_the_about_page_uses_the_base_layout(self):
        response = self.client.get(reverse("about"))
        self.assertTemplateUsed(response, "circles/base.html")
        self.assertContains(response, "About Gameya")

    def test_the_base_layout_links_back_home(self):
        response = self.client.get(reverse("about"))
        self.assertContains(response, 'href="/"')
