"""Module 04 acceptance tests: class-based views and the public Gameya API. Do not edit this file.

Run:  python manage.py test circles.tests.test_class_views

These tests use the Module 02 models and the Module 03 forms. Finish those first.

The API returns JSON. The test client does not check CSRF tokens, so these tests can POST.
A real browser form needs a token (module 05), and curl gets 403 until module 11.
"""

from datetime import date

from django.test import TestCase
from django.urls import reverse
from django.views.generic import DetailView

# Import the module, not the names: a missing view then fails only its own tests.
from circles import views as circle_views
from circles.models import Gameya, Member, Payment


def make_gameya(**overrides):
    values = {
        "name": "Alpha",
        "start_date": date(2026, 10, 11),
        "weeks": 10,
        "per_week": 1,
        "share_value": 500,
    }
    values.update(overrides)
    return Gameya.objects.create(**values)


class GameyaListTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        # Created out of name order, so reverse creation order cannot pass for name order.
        make_gameya(name="Beta", weeks=10, share_value=500)
        make_gameya(name="Gamma", weeks=10, share_value=500)
        cls.alpha = make_gameya(name="Alpha", weeks=12, share_value=300)

    def test_lists_gameyas_by_name_as_json(self):
        response = self.client.get(reverse("gameya_list"))
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response["Content-Type"], "application/json")
        self.assertEqual(
            [item["name"] for item in response.json()],
            ["Alpha", "Beta", "Gamma"],
        )

    def test_each_item_has_exactly_the_public_fields(self):
        item = self.client.get(reverse("gameya_list")).json()[0]
        self.assertEqual(
            item,
            {"id": self.alpha.pk, "name": "Alpha", "weeks": 12, "share_value": 300},
        )

    def test_q_matches_a_part_of_the_name_ignoring_case(self):
        # "LPH" is in the middle of "Alpha", so a startswith() lookup would miss it.
        # On SQLite, contains() already ignores case for ASCII letters, so this test cannot
        # tell contains() from icontains(). The lesson explains why icontains is the right one.
        response = self.client.get(reverse("gameya_list"), {"q": "LPH"})
        self.assertEqual([item["name"] for item in response.json()], ["Alpha"])

    def test_q_matches_the_start_of_the_name_ignoring_case(self):
        response = self.client.get(reverse("gameya_list"), {"q": "ALP"})
        self.assertEqual([item["name"] for item in response.json()], ["Alpha"])

    def test_no_match_gives_an_empty_list(self):
        response = self.client.get(reverse("gameya_list"), {"q": "zzz"})
        self.assertEqual(response.json(), [])

    def test_post_is_not_allowed(self):
        self.assertEqual(self.client.post(reverse("gameya_list")).status_code, 405)


class GameyaDetailTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.gameya = make_gameya(name="Alpha", weeks=10, per_week=2, share_value=100)

    def test_returns_the_gameya_with_its_figures(self):
        response = self.client.get(reverse("gameya_detail", args=[self.gameya.pk]))
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response["Content-Type"], "application/json")
        self.assertEqual(
            response.json(),
            {
                "id": self.gameya.pk,
                "name": "Alpha",
                "weeks": 10,
                "per_week": 2,
                "share_value": 100,
                "turns": 20,
                "payout": 1000,
                "weekly_pot": 2000,
            },
        )

    def test_an_unknown_gameya_is_404(self):
        response = self.client.get(reverse("gameya_detail", args=[9999]))
        self.assertEqual(response.status_code, 404)

    def test_post_is_not_allowed(self):
        url = reverse("gameya_detail", args=[self.gameya.pk])
        self.assertEqual(self.client.post(url).status_code, 405)

    def test_the_detail_view_builds_its_own_json(self):
        # The page must be a DetailView, and must override render_to_response().
        self.assertTrue(issubclass(circle_views.GameyaDetail, DetailView))
        self.assertIsNot(
            circle_views.GameyaDetail.render_to_response,
            DetailView.render_to_response,
        )


class GameyaPaymentsTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.gameya = make_gameya(name="Alpha", weeks=10, share_value=500)
        cls.other = make_gameya(name="Beta", weeks=10, share_value=500)
        # Ali has two shares, so a week costs him 2 * 500 = 1000.
        cls.ali = Member.objects.create(gameya=cls.gameya, name="Ali", shares=2)
        cls.sara = Member.objects.create(gameya=cls.other, name="Sara", shares=1)
        # Created out of week order (2, then 4, then 1), so reverse creation order cannot pass.
        cls.week2 = Payment.objects.create(
            member=cls.ali, week=2, paid_on=date(2026, 10, 18), amount=1000
        )
        cls.week4 = Payment.objects.create(
            member=cls.ali, week=4, paid_on=date(2026, 11, 8), amount=1000
        )
        cls.week1 = Payment.objects.create(
            member=cls.ali, week=1, paid_on=date(2026, 10, 11), amount=1000
        )
        Payment.objects.create(member=cls.sara, week=1, paid_on=date(2026, 10, 11), amount=500)

    def url(self, gameya=None):
        return reverse("gameya_payments", args=[(gameya or self.gameya).pk])

    def test_lists_only_this_gameyas_payments_in_week_order(self):
        response = self.client.get(self.url())
        self.assertEqual(response.status_code, 200)
        self.assertEqual(
            response.json(),
            [
                {
                    "id": self.week1.pk,
                    "member": "Ali",
                    "week": 1,
                    "amount": 1000,
                    "paid_on": "2026-10-11",
                },
                {
                    "id": self.week2.pk,
                    "member": "Ali",
                    "week": 2,
                    "amount": 1000,
                    "paid_on": "2026-10-18",
                },
                {
                    "id": self.week4.pk,
                    "member": "Ali",
                    "week": 4,
                    "amount": 1000,
                    "paid_on": "2026-11-08",
                },
            ],
        )

    def test_the_list_runs_a_fixed_number_of_queries(self):
        # One query for the gameya, and one for the payments with their members.
        # Without select_related("member") this grows with every payment.
        with self.assertNumQueries(2):
            self.client.get(self.url())

    def test_a_valid_payment_is_saved_and_returns_201(self):
        response = self.client.post(
            self.url(),
            {"member": self.ali.pk, "week": 3, "paid_on": "2026-10-25", "amount": 1000},
        )
        self.assertEqual(response.status_code, 201)
        saved = Payment.objects.get(member=self.ali, week=3)
        self.assertEqual(
            response.json(),
            {
                "id": saved.pk,
                "member": "Ali",
                "week": 3,
                "amount": 1000,
                "paid_on": "2026-10-25",
            },
        )

    def test_an_amount_below_the_due_returns_400_with_the_error(self):
        response = self.client.post(
            self.url(),
            {"member": self.ali.pk, "week": 3, "paid_on": "2026-10-25", "amount": 999},
        )
        self.assertEqual(response.status_code, 400)
        errors = response.json()["errors"]
        self.assertEqual(set(errors["amount"][0]), {"message", "code"})
        self.assertFalse(Payment.objects.filter(member=self.ali, week=3).exists())

    def test_a_member_from_another_gameya_is_rejected_on_the_member_field(self):
        response = self.client.post(
            self.url(),
            {"member": self.sara.pk, "week": 3, "paid_on": "2026-10-25", "amount": 500},
        )
        self.assertEqual(response.status_code, 400)
        errors = response.json()["errors"]
        self.assertIn("member", errors)
        self.assertEqual(set(errors["member"][0]), {"message", "code"})
        self.assertFalse(Payment.objects.filter(member=self.sara, week=3).exists())

    def test_a_second_payment_for_the_same_week_is_reported_under_all(self):
        response = self.client.post(
            self.url(),
            {"member": self.ali.pk, "week": 1, "paid_on": "2026-10-11", "amount": 1000},
        )
        self.assertEqual(response.status_code, 400)
        errors = response.json()["errors"]
        self.assertIn("__all__", errors)
        self.assertEqual(set(errors["__all__"][0]), {"message", "code"})

    def test_an_unknown_gameya_is_404_for_get_and_post(self):
        url = reverse("gameya_payments", args=[9999])
        self.assertEqual(self.client.get(url).status_code, 404)
        self.assertEqual(self.client.post(url, {}).status_code, 404)

    def test_put_is_not_allowed(self):
        self.assertEqual(self.client.put(self.url()).status_code, 405)
