"""Module 02 acceptance tests for the models. Do not edit this file.

Run:  python manage.py test circles.tests.test_models
"""

from datetime import UTC, date, datetime

from django.core.exceptions import ValidationError
from django.core.management import call_command
from django.db import IntegrityError, transaction
from django.test import TestCase

from circles.models import Gameya, Member, Payment, PayoutSlot


def make_gameya(**overrides):
    values = {
        "name": "Alf",
        "start_date": date(2026, 10, 10),  # a Saturday
        "weeks": 4,
        "per_week": 2,
        "share_value": 100,
    }
    values.update(overrides)
    return Gameya.objects.create(**values)


class MigrationTests(TestCase):
    def test_migrations_are_up_to_date(self):
        """If this fails, run: python manage.py makemigrations"""
        try:
            call_command("makemigrations", "--check", "--dry-run", verbosity=0)
        except SystemExit:
            self.fail("Your models changed but there is no migration. Run makemigrations.")


class GameyaTests(TestCase):
    def test_str_is_the_name(self):
        assert str(make_gameya(name="Alf")) == "Alf"

    def test_defaults_and_created_at(self):
        g = Gameya.objects.create(name="X", start_date=date(2026, 1, 3), weeks=2, share_value=5)
        assert g.per_week == 1
        assert g.created_at is not None

    def test_derived_figures(self):
        g = make_gameya(weeks=10, per_week=2, share_value=100)
        assert (g.turns, g.payout, g.weekly_pot) == (20, 1000, 2000)

    def test_week_start_and_pay_window(self):
        g = make_gameya()
        assert g.week_start(1) == date(2026, 10, 10)
        assert g.week_start(3) == date(2026, 10, 24)
        assert g.pay_window_start(1) == date(2026, 10, 4)  # the Sunday before
        assert g.pay_window_start(2) == date(2026, 10, 11)

    def test_pay_window_for_a_sunday_payout_is_that_day(self):
        g = make_gameya(start_date=date(2026, 10, 11))
        assert g.pay_window_start(1) == date(2026, 10, 11)

    def test_gameyas_are_ordered_by_name(self):
        make_gameya(name="Zed")
        make_gameya(name="Alf")
        assert [g.name for g in Gameya.objects.all()] == ["Alf", "Zed"]

    def test_the_database_rejects_non_positive_numbers(self):
        for field in ("weeks", "per_week", "share_value"):
            with self.subTest(field=field), self.assertRaises(IntegrityError):
                with transaction.atomic():
                    make_gameya(**{field: 0})


class MemberTests(TestCase):
    def setUp(self):
        self.g = make_gameya()

    def test_str_and_defaults(self):
        m = Member.objects.create(gameya=self.g, name="Ali")
        assert str(m) == "Ali (Alf)"
        assert m.shares == 1

    def test_due_is_shares_times_share_value(self):
        m = Member.objects.create(gameya=self.g, name="Ali", shares=3)
        assert m.due() == 300

    def test_reverse_relation_is_called_members(self):
        Member.objects.create(gameya=self.g, name="Ali")
        Member.objects.create(gameya=self.g, name="Sara")
        assert self.g.members.count() == 2

    def test_a_name_is_unique_within_one_gameya_only(self):
        Member.objects.create(gameya=self.g, name="Ali")
        with self.assertRaises(IntegrityError), transaction.atomic():
            Member.objects.create(gameya=self.g, name="Ali")
        other = make_gameya(name="Other")
        Member.objects.create(gameya=other, name="Ali")  # fine in a different gameya

    def test_deleting_a_gameya_deletes_its_members_and_payments(self):
        m = Member.objects.create(gameya=self.g, name="Ali")
        Payment.objects.create(member=m, week=1, paid_on=date(2026, 10, 5), amount=100)
        self.g.delete()
        assert Member.objects.count() == 0 and Payment.objects.count() == 0

    def test_members_keep_creation_order(self):
        for name in ("Zed", "Amr", "Mona"):
            Member.objects.create(gameya=self.g, name=name)
        assert [m.name for m in self.g.members.all()] == ["Zed", "Amr", "Mona"]


class PaymentTests(TestCase):
    def setUp(self):
        self.g = make_gameya()
        self.ali = Member.objects.create(gameya=self.g, name="Ali")

    def pay(self, week, paid_on, amount=100):
        return Payment.objects.create(member=self.ali, week=week, paid_on=paid_on, amount=amount)

    def test_str(self):
        assert str(self.pay(1, date(2026, 10, 5))) == "Ali: week 1"

    def test_one_payment_per_member_per_week(self):
        self.pay(1, date(2026, 10, 5))
        with self.assertRaises(IntegrityError), transaction.atomic():
            self.pay(1, date(2026, 10, 6))
        self.pay(2, date(2026, 10, 12))  # another week is fine

    def test_clean_rejects_weeks_outside_the_gameya(self):
        for week in (0, 5, 99):
            with self.subTest(week=week), self.assertRaises(ValidationError):
                Payment(
                    member=self.ali, week=week, paid_on=date(2026, 10, 5), amount=1
                ).full_clean()
        Payment(member=self.ali, week=4, paid_on=date(2026, 10, 5), amount=1).full_clean()

    def test_is_advance_compares_with_the_window_opening(self):
        assert self.pay(1, date(2026, 10, 4)).is_advance is False  # window opens that day
        assert self.pay(2, date(2026, 10, 10)).is_advance is True  # window opens 10-11
        assert self.pay(3, date(2026, 10, 18)).is_advance is False

    def test_payments_are_ordered_by_week(self):
        self.pay(3, date(2026, 10, 18))
        self.pay(1, date(2026, 10, 5))
        assert [p.week for p in self.ali.payments.all()] == [1, 3]


class MemberStatusTests(TestCase):
    def setUp(self):
        self.g = make_gameya()
        self.ali = Member.objects.create(gameya=self.g, name="Ali")

    def test_upcoming_before_the_payout_day_and_unpaid_from_it(self):
        assert self.ali.status(1, today=date(2026, 10, 9)) == "upcoming"
        assert self.ali.status(1, today=date(2026, 10, 10)) == "unpaid"
        assert self.ali.status(2, today=date(2026, 10, 12)) == "upcoming"

    def test_paid_inside_the_window(self):
        Payment.objects.create(member=self.ali, week=1, paid_on=date(2026, 10, 5), amount=100)
        assert self.ali.status(1, today=date(2026, 10, 12)) == "paid"
        assert self.ali.status(1, today=date(2026, 10, 6)) == "paid"  # even before the payout day

    def test_advance_before_the_window(self):
        Payment.objects.create(member=self.ali, week=2, paid_on=date(2026, 10, 4), amount=100)
        assert self.ali.status(2, today=date(2026, 10, 6)) == "advance"


class PayoutSlotTests(TestCase):
    def setUp(self):
        self.g = make_gameya()  # per_week = 2

    def test_str_and_week(self):
        slot = PayoutSlot.objects.create(gameya=self.g, turn_number=3)
        assert str(slot) == "Turn 3 (week 2)"
        assert [PayoutSlot(gameya=self.g, turn_number=n).week for n in (1, 2, 3, 4, 5)] == [
            1,
            1,
            2,
            2,
            3,
        ]

    def test_a_slot_starts_with_no_member_and_not_delivered(self):
        slot = PayoutSlot.objects.create(gameya=self.g, turn_number=1)
        assert slot.member is None and slot.delivered_at is None

    def test_turn_numbers_are_unique_per_gameya(self):
        PayoutSlot.objects.create(gameya=self.g, turn_number=1)
        with self.assertRaises(IntegrityError), transaction.atomic():
            PayoutSlot.objects.create(gameya=self.g, turn_number=1)

    def test_deleting_the_member_keeps_the_slot_but_clears_the_holder(self):
        ali = Member.objects.create(gameya=self.g, name="Ali")
        slot = PayoutSlot.objects.create(gameya=self.g, turn_number=1, member=ali)
        assert list(ali.slots.all()) == [slot]
        ali.delete()
        slot.refresh_from_db()
        assert slot.member is None

    def test_slots_are_ordered_by_turn_and_reachable_from_the_gameya(self):
        for n in (3, 1, 2):
            PayoutSlot.objects.create(gameya=self.g, turn_number=n)
        assert [s.turn_number for s in self.g.slots.all()] == [1, 2, 3]

    def test_delivered_at_stores_a_timezone_aware_datetime(self):
        when = datetime(2026, 10, 10, 18, 30, tzinfo=UTC)
        slot = PayoutSlot.objects.create(gameya=self.g, turn_number=1, delivered_at=when)
        slot.refresh_from_db()
        assert slot.delivered_at == when
